---
version: "3.5"

services:
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: film_locations
      DB_USER: film_locations_user
      DB_PASS: film_locations_pass
    volumes:
      - ./data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./data/mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019
  get_film_locations:
    build:
      context: .
      dockerfile: Dockerfile
    image: get_film_locations:local
    container_name: get_film_locations
    command: bash -c "npm start"
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: film_locations_user
      DB_PASS: film_locations_pass
      DB_NAME: film_locations
      DB_BULK_OP_MAX_SIZE: 50000
      MAX_CONCURRENT_REQUESTS: 10
    volumes:
      - .:/usr/src/app
    ports:
      - 9229:9229
