---
version: "3.5"

services:
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: film_locations
      DB_USER: film_locations_user
      DB_PASS: film_locations_pass
    volumes:
      - ./data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./data/mongo-volume:/data/db
      - ./data/backups:/data/backups
    ports:
      - 27017-27019:27017-27019
  get_film_locations:
    build:
      context: .
      dockerfile: Dockerfile
    image: get-film-locations:local
    container_name: get_film_locations
    command: bash -c "npm run generate-db"
    environment:
      ENVIRONMENT: local
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: film_locations_user
      DB_PASS: film_locations_pass
      DB_NAME: film_locations
      DB_BULK_OP_MAX_SIZE: 10000
      MAX_CONCURRENT_REQUESTS: 10
      PORT: ${PORT:-8080}
    volumes:
      - ./lib:/usr/src/app/lib
      - ./credentials:/usr/src/app/credentials
      - ./scripts:/usr/src/app/scripts
    ports:
      - 9229:9229
      - 8080:${PORT:-8080}
  film_locations:
    build:
      context: .
      dockerfile: Dockerfile
    image: film-locations:local
    container_name: film_locations
    command: bash -c "npm run server-dev"
    environment:
      ENVIRONMENT: local
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: film_locations_user
      DB_PASS: film_locations_pass
      DB_NAME: film_locations
      PORT: 5000
    volumes:
      - ./lib:/usr/src/app/lib
      - ./credentials:/usr/src/app/credentials
      - ./server:/usr/src/app/server
      - ./scripts:/usr/src/app/scripts
    ports:
      - 5000:5000
      - 9229:9229
  film_locations_dev_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: film-locations-dev-server:local
    container_name: film_locations_dev_server
    command: bash -c "npm run client-dev"
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - 3000:3000
