apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-locations-deployment
  labels:
    app: film-locations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: film-locations
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: film-locations
    spec:
      containers:
        - image: gcr.io/filmlocations/film-locations:1.3.1
          imagePullPolicy: Always
          name: film-locations
      restartPolicy: Always
