apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-locations-deployment
  labels:
    app: film-locations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: film-locations
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: film-locations
    spec:
      containers:
        - image: gcr.io/filmlocations/film-locations:1.4.1
          imagePullPolicy: Always
          name: film-locations
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: film-locations-db-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: film-locations-db-secret
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: film-locations-db-secret
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: film-locations-db-secret
                  key: pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: film-locations-db-secret
                  key: name
            - name: CACHE_HOST
              value: 'redis'
            - name: CACHE_PORT
              value: '6379'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
      restartPolicy: Always
