apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2020-02-28T01:40:38Z"
  generation: 4
  labels:
    app: film-locations
  name: film-locations
  namespace: default
  resourceVersion: "543357"
  selfLink: /apis/apps/v1/namespaces/default/deployments/film-locations
  uid: 527fe65f-59cb-11ea-b1c6-42010a8e0125
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: film-locations
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: film-locations
    spec:
      containers:
      - image: gcr.io/filmlocations/film-locations:1.1.0
        imagePullPolicy: IfNotPresent
        name: film-locations
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
